version: 2
python_env: &python_env
  docker:
    - image: circleci/python:2.7-stretch-browsers
    
install_awscli: &install_awscli
  name: "Install awscli"
  command: |
    sudo pip install awscli --upgrade
install_deploysuite: &install_deploysuite
          name: Installation of install_deploysuite.
          command: |
            git clone --branch dev_comm https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .
            
# Instructions of deployment
deploy_steps: &deploy_steps
  - checkout
  - attach_workspace:
      at: ./workspace
  - run: *install_awscli
  - run: *install_deploysuite
  - setup_remote_docker
  - run: cd consumer && docker build -t tc-connect2sf:latest .
  - deploy:
      name: "Running Masterscript -  deploy tc-connect2sf " 
      command: |
        # cd consumer
        ./awsconfiguration.sh $DEPLOY_ENV  
        source awsenvconf
        ./buildenv.sh -e $DEPLOY_ENV -b ${VAR_ENV}-tc-connect2sf-service-deployvar
        source buildenvvar
        ./master_deploy.sh -d ECS -e $DEPLOY_ENV -t latest -s ${VAR_ENV}-global-appvar,${VAR_ENV}-tc-connect2sf-service-appvar -i tc-connect2sf

        echo "======= Running Masterscript - deploy tc-connect2sf-consumers ==========="
        if [ -e ${VAR_ENV}-tc-connect2sf-service-appvar.json ]; then  sudo rm -vf ${VAR_ENV}-tc-connect2sf-service-appvar.json; fi
        ./buildenv.sh -e $DEPLOY_ENV -b ${VAR_ENV}-tc-connect2sf-consumers-deployvar
        source buildenvvar
        ./master_deploy.sh -d ECS -e $DEPLOY_ENV -t latest -s ${VAR_ENV}-global-appvar,${VAR_ENV}-tc-connect2sf-service-appvar -i tc-connect2sf

        echo "======= Running Masterscript - deploy tc-connect2sf-salesforce-connsumers ==========="
        if [ -e ${VAR_ENV}-tc-connect2sf-service-appvar.json ]; then  sudo rm -vf ${VAR_ENV}-tc-connect2sf-service-appvar.json; fi
        ./buildenv.sh -e $DEPLOY_ENV -b ${VAR_ENV}-tc-connect2sf-salesforce-consumers-deployvar
        source buildenvvar
        ./master_deploy.sh -d ECS -e $DEPLOY_ENV -t latest -s ${VAR_ENV}-global-appvar,${VAR_ENV}-tc-connect2sf-service-appvar -i tc-connect2sf
        
jobs:
  test:
    docker:
      - image: circleci/node:8.9.4
    environment:
      LOG_LEVEL: debug
    steps:
      - checkout
      - restore_cache:
          key: test-node-modules-{{ checksum "consumer/package.json" }}
      - run: cd consumer && npm install
      - save_cache:
          key: test-node-modules-{{ checksum "consumer/package.json" }}
          paths:
            - consumer/node_modules
      # - run: cd consumer && npm run lint
      - run: cd consumer && npm run test
      # - run: cd consumer && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - consumer/node_modules
            
  deployProd:
    <<: *python_env
    environment:
      DEPLOY_ENV: "PROD"
      VAR_ENV: "prod"
    steps: *deploy_steps

  deployDev:
    <<: *python_env
    environment:
      DEPLOY_ENV: "DEV"
      VAR_ENV: "dev"
    steps: *deploy_steps 
    
workflows:
  version: 2
  build:
    jobs:
      - test
      - deployDev:
          context : org-global
          requires:
            - test
          filters:
            branches:
              only: ['dev', 'feature/event-based-salesforce-integration']